<?php
register_post_type( 'crb_team', array(
	'labels' => array(
		'name'               => __( 'Team', 'crb' ),
		'singular_name'      => __( 'Member', 'crb' ),
		'add_new'            => __( 'Add New', 'crb' ),
		'add_new_item'       => __( 'Add new Member', 'crb' ),
		'view_item'          => __( 'View Member', 'crb' ),
		'edit_item'          => __( 'Edit Member', 'crb' ),
		'new_item'           => __( 'New Member', 'crb' ),
		'view_item'          => __( 'View Member', 'crb' ),
		'search_items'       => __( 'Search Team', 'crb' ),
		'not_found'          => __( 'No Team found', 'crb' ),
		'not_found_in_trash' => __( 'No Team found in trash', 'crb' ),
	),
	'public'              => true,
	'exclude_from_search' => false,
	'show_ui'             => true,
	'capability_type'     => 'post',
	'hierarchical'        => false,
	'_edit_link'          => 'post.php?post=%d',
	'rewrite'             => array(
		'slug'       => 'team',
		'with_front' => false,
	),
	'query_var' => true,
	'menu_icon' => 'dashicons-groups',
	'supports'  => array( 'title', 'editor', 'thumbnail', 'page-attributes', 'custom-fields' ),
) );

register_post_type( 'crb_location', array(
	'labels' => array(
		'name'               => __( 'Locations', 'crb' ),
		'singular_name'      => __( 'Location', 'crb' ),
		'add_new'            => __( 'Add New', 'crb' ),
		'add_new_item'       => __( 'Add new Location', 'crb' ),
		'view_item'          => __( 'View Location', 'crb' ),
		'edit_item'          => __( 'Edit Location', 'crb' ),
		'new_item'           => __( 'New Location', 'crb' ),
		'view_item'          => __( 'View Location', 'crb' ),
		'search_items'       => __( 'Search Locations', 'crb' ),
		'not_found'          => __( 'No Locations found', 'crb' ),
		'not_found_in_trash' => __( 'No Locations found in trash', 'crb' ),
	),
	'public'              => true,
	'exclude_from_search' => false,
	'show_ui'             => true,
	'capability_type'     => 'post',
	'hierarchical'        => false,
	'_edit_link'          => 'post.php?post=%d',
	'rewrite'             => array(
		'slug'       => 'locations',
		'with_front' => false,
	),
	'query_var' => true,
	'menu_icon' => 'dashicons-location-alt',
	'supports'  => array( 'title' ),
) );

register_post_type( 'crb_help_center', array(
	'labels' => array(
		'name'               => __( 'Help Center', 'crb' ),
		'singular_name'      => __( 'Article', 'crb' ),
		'add_new'            => __( 'Add New', 'crb' ),
		'add_new_item'       => __( 'Add new Article', 'crb' ),
		'view_item'          => __( 'View Article', 'crb' ),
		'edit_item'          => __( 'Edit Article', 'crb' ),
		'new_item'           => __( 'New Article', 'crb' ),
		'view_item'          => __( 'View Article', 'crb' ),
		'search_items'       => __( 'Search Help Center', 'crb' ),
		'not_found'          => __( 'No Help Center found', 'crb' ),
		'not_found_in_trash' => __( 'No Help Center found in trash', 'crb' ),
	),
	'public'              => true,
	'exclude_from_search' => false,
	'show_ui'             => true,
	'show_in_rest'        => true,
	'capability_type'     => 'post',
	'hierarchical'        => false,
	'_edit_link'          => 'post.php?post=%d',
	'rewrite'             => array(
		'slug'       => 'help-center-articles',
		'with_front' => false,
	),
	'query_var' => true,
	'menu_icon' => 'dashicons-testimonial',
	'supports'  => array( 'title', 'editor', 'thumbnail' ),
) );

register_post_type( 'crb_area', array(
	'labels' => array(
		'name'               => __( 'Practice Areas', 'crb' ),
		'singular_name'      => __( 'Practice Area', 'crb' ),
		'add_new'            => __( 'Add New', 'crb' ),
		'add_new_item'       => __( 'Add new Practice Area', 'crb' ),
		'view_item'          => __( 'View Practice Area', 'crb' ),
		'edit_item'          => __( 'Edit Practice Area', 'crb' ),
		'new_item'           => __( 'New Practice Area', 'crb' ),
		'view_item'          => __( 'View Practice Area', 'crb' ),
		'search_items'       => __( 'Search Practice Areas', 'crb' ),
		'not_found'          => __( 'No Practice Areas found', 'crb' ),
		'not_found_in_trash' => __( 'No Practice Areas found in trash', 'crb' ),
	),
	'public'              => true,
	'exclude_from_search' => false,
	'show_ui'             => true,
	'show_in_rest'        => true,
	'capability_type'     => 'post',
	'hierarchical'        => false,
	'_edit_link'          => 'post.php?post=%d',
	'rewrite'             => array(
		'slug'       => 'practice-area',
		'with_front' => false,
	),
	'query_var' => true,
	'menu_icon' => 'dashicons-book',
	'supports'  => array( 'title' ),
) );

register_post_type( 'crb_email', array(
	'labels' => array(
		'name'               => __( 'Email Signatures', 'crb' ),
		'singular_name'      => __( 'Email Signature', 'crb' ),
		'add_new'            => __( 'Add New', 'crb' ),
		'add_new_item'       => __( 'Add new Email Signature', 'crb' ),
		'view_item'          => __( 'View Email Signature', 'crb' ),
		'edit_item'          => __( 'Edit Email Signature', 'crb' ),
		'new_item'           => __( 'New Email Signature', 'crb' ),
		'view_item'          => __( 'View Email Signature', 'crb' ),
		'search_items'       => __( 'Search Email Signature', 'crb' ),
		'not_found'          => __( 'No Email Signature found', 'crb' ),
		'not_found_in_trash' => __( 'No Email Signature found in trash', 'crb' ),
	),
	'public'              => true,
	'exclude_from_search' => false,
	'show_ui'             => true,
	'capability_type'     => 'post',
	'hierarchical'        => false,
	'_edit_link'          => 'post.php?post=%d',
	'rewrite'             => array(
		'slug'       => 'email-sig',
		'with_front' => false,
	),
	'query_var' => true,
	'menu_icon' => 'dashicons-edit',
	'supports'  => array( 'title', 'editor', 'thumbnail', 'page-attributes' ),
) );
